version: '3.3'
services:

  web:
    build: .
    ports:
     - 5000:5000

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.1
    environment:
      - server.name=kibana
      - server.host="0"
      - elasticsearch.url=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  cerebro:
    image: yannart/cerebro:latest
    ports:
      - 9000:9000
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local
