foursquare:
  client_id: FOBCAD5DAESODWQXRTZOMDQA0SZ53EJJZG5XUQAVYGIYBTIQ
  client_secret: 4GMOZAWUBUUHEWJ3LCDI5RM15VTNBMJUT1MPZ2SWBUYS1C5V
facebook:
  app_id: 309731039529164
  app_secret: dc714ec4faf5125f1da7a47a1b953a54
  access_token: 309731039529164|pjS5PDnT_Qjzlymw7J5keH0YBbc
